### PR TITLE
New tas

### PR DESCRIPTION
**Pull request by brayzen**
I was hesitant to remove others' code, so I kept it and made my own.  Progress bar added.  thanx-message displays upon submittion of petition.  

@ivanoats It does have some logic that Trish may want to use later, letters to politicians etc that I won't be incorporating.  I'm ok to get rid of it.  -brayzen

### CODE REVIEW

**Comment by ivanoats** [comment]
Can the commented out code just be removed?

**Comment by Trishthedish** [comment]
@brayzen if its the letter wording, any chance you can copy and paste it into a google doc?

**Comment by AndyCErnst** [comment]
The css file is not needed, as only less files are copied over to the dist directory. 

If we are building this site for production, we should stay away from using px. If we use rem everywhere instead of px, we can avoid display bugs when users increase the font size. Our css reset framework sets the base html font size to 10px so anywhere on the page you can use 1rem as equivalent to 10px.

I'm fine with deleting the slider javascript.

**Comment by brayzen** [comment]
Ok, so I cleaned up everything, but my CSS isn't working like I want.....my media queries don't seem to be working the way I have them in LESS....all borders are just for my sake trying to figure out the layout(which is something I'm trying to get better at).

**Comment by AndyCErnst** [comment]
At least one of your media queries doesn't have a selector inside of it. I think you always have to specify the selector inside of the query, both for css and less. Like this:
 @media (max-width: 600px) {
    h1 {
      color: red;
    }
}

I'm merging this PR.

**Pull request merged**
